apiVersion: v1
kind: Service
metadata:
  name: idrak-app
  namespace: app
spec:
  selector:
    app: idrak-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
