apiVersion: v1
kind: Secret
metadata:
  name: diary-secret
  namespace: app
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:admin123@idrak-db:27017/admin?authSource=admin
  DB_USER: admin
  DB_PASSWORD: admin123
  ADMIN_USER: admin
  ADMIN_PASSWORD: admin123
  EMPLOYEE_USER: empoly
  EMPLOYEE_PASSWORD: empolydata

