apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-mongo-data
  persistentVolumeReclaimPolicy: Retain
